services:
  web:
    build:
      context: .
      target: builder
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/html/
    environment:
      - DB_HOST=mysql
      - DB_NAME=localdb
      - DB_USER=localuser
      - DB_PASSWORD=localpw
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: localdb
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpw
    command: --default-authentication-plugin=mysql_native_password  # Use mysql_native_password for compatibility

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
